const keys = {
  iconExtract: "iconExtract",
  iconExtractForm: "iconExtractForm",
  iconExtractTitle: "iconExtractTitle",
  iconExtractFormInputBox: "iconExtractFormInputBox",
  frameLabel: "frameLabel",
  frame: "frame",
  figmaTokenLabel: "figmaTokenLabel",
  figmaToken: "figmaToken",
  githubTokenLabel: "githubTokenLabel",
  githubToken: "githubToken",
  extractRouteLabel: "extractRouteLabel",
  extractRoute: "extractRoute",
  iconExtractStepButtonContainer: "iconExtractStepButtonContainer",
  iconExtractFormSubmitButton: "iconExtractFormSubmitButton",
  iconExtractFormCancelButton: "iconExtractFormCancelButton",
} as const;

export default {
  iconExtract: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    backgroundColor: "#f5f5f7",
  },
  iconExtractForm: {
    width: "100%",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    borderRadius: "10px",
    backgroundColor: "white",
  },
  iconExtractTitle: {
    textAlign: "center",
    marginBottom: "20px",
    fontSize: "24px",
    color: "#333",
  },
  iconExtractFormInputBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "16px",
  },
  frameLabel: {
    display: "block",
    marginBottom: "8px",
    fontSize: "14px",
    color: "#333",
  },
  frame: {
    width: "100%",
    padding: "10px",
    fontSize: "16px",
    border: "1px solid #ccc",
    borderRadius: "5px",
    boxSizing: "border-box",
  },
  figmaTokenLabel: {
    display: "block",
    marginBottom: "8px",
    fontSize: "14px",
    color: "#333",
  },
  figmaToken: {
    width: "100%",
    padding: "10px",
    fontSize: "16px",
    border: "1px solid #ccc",
    borderRadius: "5px",
    boxSizing: "border-box",
  },
  githubTokenLabel: {
    display: "block",
    marginBottom: "8px",
    fontSize: "14px",
    color: "#333",
  },
  githubToken: {
    width: "100%",
    padding: "10px",
    fontSize: "16px",
    border: "1px solid #ccc",
    borderRadius: "5px",
    boxSizing: "border-box",
  },
  extractRouteLabel: {
    display: "block",
    marginBottom: "8px",
    fontSize: "14px",
    color: "#333",
  },
  extractRoute: {
    width: "100%",
    padding: "10px",
    fontSize: "16px",
    border: "1px solid #ccc",
    borderRadius: "5px",
    boxSizing: "border-box",
  },
  iconExtractStepButtonContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "16px",
    marginTop: "20px",
  },
  iconExtractFormSubmitButton: {
    width: "100%",
    padding: "10px",
    backgroundColor: "#007bff",
    color: "white",
    border: "none",
    borderRadius: "5px",
    fontSize: "16px",
    cursor: "pointer",
  },
  iconExtractFormCancelButton: {
    width: "100%",
    padding: "10px",
    backgroundColor: "#6c757d",
    color: "white",
    border: "none",
    borderRadius: "5px",
    fontSize: "16px",
    cursor: "pointer",
  },
} as Record<keyof typeof keys, React.CSSProperties>;
